import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Autogenerated from the docs/ tree. Ordering is controlled by each file's
 * `sidebar_position` front-matter and by _category_.json files.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
